// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxtUw-1g2HuBoKBtNOwbQoB0J9g3-sl0s',
    appId: '1:427379084898:web:cf893da4356ab921828b3b',
    messagingSenderId: '427379084898',
    projectId: 'tnotification-3abce',
    authDomain: 'tnotification-3abce.firebaseapp.com',
    storageBucket: 'tnotification-3abce.firebasestorage.app',
    measurementId: 'G-D7SWYH7M7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeQjH2CLfzDZWpMpVR1dFt9osaK5qV13Y',
    appId: '1:427379084898:android:18832d933d617ac7828b3b',
    messagingSenderId: '427379084898',
    projectId: 'tnotification-3abce',
    storageBucket: 'tnotification-3abce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfQTIucq9sFFrir3nG1GUBotg0PK9eKSQ',
    appId: '1:427379084898:ios:34a66bb462b97add828b3b',
    messagingSenderId: '427379084898',
    projectId: 'tnotification-3abce',
    storageBucket: 'tnotification-3abce.firebasestorage.app',
    iosBundleId: 'com.example.taskproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfQTIucq9sFFrir3nG1GUBotg0PK9eKSQ',
    appId: '1:427379084898:ios:34a66bb462b97add828b3b',
    messagingSenderId: '427379084898',
    projectId: 'tnotification-3abce',
    storageBucket: 'tnotification-3abce.firebasestorage.app',
    iosBundleId: 'com.example.taskproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxtUw-1g2HuBoKBtNOwbQoB0J9g3-sl0s',
    appId: '1:427379084898:web:b8ac17b2a9c47ade828b3b',
    messagingSenderId: '427379084898',
    projectId: 'tnotification-3abce',
    authDomain: 'tnotification-3abce.firebaseapp.com',
    storageBucket: 'tnotification-3abce.firebasestorage.app',
    measurementId: 'G-HX2VNHE1Y4',
  );
}
